[pytest]

log_file = test.log
log_file_mode = w
log_file_level = DEBUG
log_format = %(asctime)s - %(levelname)s - %(message)s

marker = 
    system: marker to the system test
    unit: used to test components
    wip:work in progress
